os:
  - linux
  - osx
language: csharp
solution: Source/V8.Net.MonoDevelop.sln
install: 
  - sudo apt-get install build-essential subversion git git-svn libglib2.0-dev g++-multilib gcc-4.8 gcc-4.8-base
script:
  - ./build_V8_Net.sh -d x64.release 2
