os:
  - linux
  - osx
language: csharp
solution: Source/V8.Net.MonoDevelop.sln
install: 
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8   
  - sudo apt-get install build-essential subversion git git-svn libglib2.0-dev g++-multilib 
script:
  - ./build_V8_Net.sh -d x64.release 2
